services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: "8.4"
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: modus-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURITY: ""
    depends_on:
      - mailhog
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: modus-mailhog
    ports:
      - "8025:8025"
    restart: unless-stopped
