services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        PHP_VERSION: "8.1"
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: modus-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
