blueprint: page

title: Tags

icon: ticket

options:
  access:
    contributeur: false
  changeSlug: false
  delete: false
  changeTitle: false
  sort: false
  changeStatus: false
  duplicate: false
  update:
    contributeur: false
  move:
    contributeur: false

sections:
  tags:
    type: pages
    templates: tag
    create: tag
    headline: Liste des étiquettes
    image: false
    layout: table
    columns:
      description:
        label: Description
        value: "{{ page.description }}"
